<?php

namespace Models;

class Customer {
    public $id;
    public $uid;
    public $email;
    public $name;
    public $address;

    public function __construct($id, $uid, $email, $name, $address) {
        $this->id       = $id;
        $this->uid      = $uid; // auto generated by random_bytes(6) to make it unique
        $this->email    = $email;
        $this->name     = $name;
        $this->address  = $address;
    }
}